### PR TITLE
Updated class.MD

### PR DESCRIPTION
**Pull request by patriciamtchll**
I have updated the markdown file.

### CODE REVIEW

**Comment by RahmanJas** [comment]
I have updated the markdown file

**Comment by trevorfrayne** [comment]
I have updated the markdown file.

**Comment by Kari3as** [comment]
I have updated the markdown file.

**Comment by DevStudent80** [comment]
I have updated the markdown file.

**Comment by wcodersv** [comment]
I have updated the markdown file.

**Comment by Kingoruovie** [comment]
I have updated the markdown file.

**Comment by EoverE** [comment]
I have updated the markdown file.

**Comment by ayu-shah0912** [comment]
I have updated the markdown file.

**Comment by sanyomor-01** [comment]
i have updated the markdown file

**Comment by muhileswaran** [comment]
i have updated the markdown file

**Comment by MyPalG** [comment]
succesfull

**Comment by Anthoun070201** [comment]
I have updated the markdown file.

**Comment by natalienutm** [comment]
Natalie commit

**Comment by Akosua96** [comment]
I have updated the markdown file.

**Comment by Boroda70** [comment]
I have updated the markdown file

**Comment by riyadhussain** [comment]
I have updated the markdown file.

**Comment by Bashir-Kalyesubula** [comment]
i have updated the markdown file

**Comment by Kiran-Alex** [comment]
i have updated the markdown file

**Comment by Nk6513** [comment]
I have updated the markdown file

**Comment by Amandzia** [comment]
I have updated the markdown file

**Comment by gkwoode** [comment]
merging exercise

**Comment by riggaaron** [comment]
i have updated the markdown file

**Comment by Olive3ree** [comment]
I have updated the markdown file.

**Comment by drleejin** [comment]
**Updated class.md file as per instructions!**

1. Testing 1
2. Testing 2

**Comment by scorpydan** [comment]
i have updated the markdown file

**Comment by sadjii** [comment]
I have updated the markdown file

**Comment by BatuAksut** [comment]
I have updated the markdown file

**Comment by BatuAksut** [comment]
I have updated the markdown file

**Comment by EnderValdivieso** [comment]
I have updated the markdown file.

**Comment by RubenOchoaPerez** [comment]
> I have updated the markdown file.

**Comment by gwenlao** [comment]
i have updated the markdown file.

**Comment by eriszn** [comment]
.

**Comment by ArpanIng** [comment]
I have updated the markdown file.

**Comment by IzaanArain** [comment]
I Izaan have updated the markdown file.

**Comment by michaelstrandjord** [comment]
I have updated the markdown file

**Comment by mvkrishna** [comment]
I have updated the markdown file

**Comment by jjeasiah** [comment]
I have updated the markdown file.

**Comment by Abenga-Philip** [comment]
I have updated the markdown file.

**Comment by stonemasonn** [comment]
I've updated the markdown file.

**Comment by batiago20** [comment]
I have updated the markdown file

**Comment by armexx** [comment]
i have updated the markdown file.

**Comment by ncheeHPU** [comment]
I have updated the markdown file.

**Comment by MarkCodering** [comment]
I have updated the markdown file.

**Comment by DhanasekaranDolphine** [comment]
I have updated the change in forking successfully

**Comment by scott-matkosky** [comment]
updated markdown file

**Comment by linhstars** [comment]
I have updated the markdown file.

**Comment by clgilchr** [comment]
I have updated the markdown file

**Comment by Jaycock2018** [comment]
I have updated the markdown file.

**Comment by iamoluwaseuno** [comment]
I have updated the markdown file.

**Comment by yanpin0524** [comment]
I have updated the markdown file.

**Comment by g232629** [comment]
I have updated the markdown file.

**Comment by g232629** [comment]
I have updated the markdown file.

**Comment by SimonRezene** [comment]
I have updated the markdown file.

**Comment by anthonyapitchou** [comment]
I have updated the markdown file.

**Comment by anthonyapitchou** [comment]
I have updated the markdown file.

**Comment by dcarty01** [comment]
I updated the markdown file

**Comment by BrandNewReplicant** [comment]
I have updated the markdown file.

**Comment by Energyzor** [comment]
I have updated the markdown file.

**Comment by PapaMaclin** [comment]
I have update the markdown file

**Comment by AkshitGulyan** [comment]
I have update the markdown file

**Comment by perriemm9** [comment]
I have updated the markdown file.

**Comment by J3SSY-ANDU** [comment]
I have updated the markdown file.

**Comment by Krrisantan** [comment]
I have updated the markdown file

**Comment by sheepnir** [comment]
I have updated the markdown file.

**Comment by YaninaGolubenko** [comment]
I have updated the markdown file.

**Comment by YaninaGolubenko** [comment]
I have updated the markdown file.

**Comment by Colocosa** [comment]
I have update the markdown file.

**Comment by endedwrock** [comment]
I have update the markdown file.

**Comment by AdamuAzarema** [comment]
I have updated the markdown file.

**Comment by jtdub** [comment]
I have updated the markdown file.

**Comment by Ismaelish** [comment]
I have updated the markdown file.

**Comment by danjacob1** [comment]
I have updated the markdown file.

**Comment by VaibhavGupta911** [comment]
I have updated the markdown file.

**Comment by jonim-git** [comment]
I have updated the markdown file.

**Comment by dayathapa1234** [comment]
I have updated the markdown file.

**Comment by Ethiomesi2020** [comment]
I have updated the markdown file.

**Comment by ynccsyd** [comment]
I have updated the markdown file.

**Comment by Caleb-Leung-Kwan-Ho** [comment]
I have updated the markdown file.

**Comment by troytoon** [comment]
I have updated the markdown file.

**Comment by kendicey** [comment]
I have updated the markdown file.

**Comment by joseluisn26-code** [comment]
I have update the markdown file.

**Comment by fmwega** [comment]
I have updated the markdown file.

**Comment by GandeDeSa** [comment]
I have updated the markdown file.

**Comment by Aishat452** [comment]
I have updated the markdown files

**Comment by pinoycaster** [comment]
I have updated the markdown file

**Comment by BilalHamzaCaptain** [comment]
Did it in coursera course of version control from meta

**Comment by Niiforex11** [comment]
i have updated it

**Comment by xVicV** [comment]
I have updated the markdown file.

**Comment by gagan77** [comment]
I have updated the markdown file.

**Comment by diogoestima1998** [comment]
I have updated the markdown file

**Comment by Mohammadalayan** [comment]
.

**Comment by tnjiit** [comment]
I have updatd the markdown file.

**Comment by andrewlit10** [comment]
I have updated the markdown file.

**Comment by anasfsimoes** [comment]
I have updated the markdown file.

**Comment by hend178** [comment]
I have updated the markdown file

**Comment by abdiysf** [comment]
I have updated the markdown file.

**Comment by Sol-Devloper** [comment]
I have updated the markdown file

**Comment by o-dunsin** [comment]
I have updated the markdown file

**Comment by JaredSoto8** [comment]
I have updated the markdown file

**Comment by Dark5kull** [comment]
I have updated the markdown file.

**Comment by AyemyaThi** [comment]
I have updated the markdown file.

**Comment by pshtiwan-hassan** [comment]
I have updated the markdown file.

**Comment by jonathanfreese** [comment]
I have updated the markdown file.

**Comment by jemima-lopez** [comment]
> I have updated the markdown file. yessss

**Comment by manojprmk** [comment]
I have updated the markdown file.

**Comment by nabhatra** [comment]
I have updated the markdown file.

**Comment by nadunwee** [comment]
I have updated the markdown file.

**Comment by Yaqub-naqeb** [comment]
jn

**Comment by m-maatallah** [comment]
I have updated the markdown file.

**Comment by Larry8900** [comment]
i have update the markdown file.

**Comment by htchik** [comment]
I have updated the markdown file

**Comment by derrek321yr** [comment]
I have updated the markdown file

**Comment by derrek321yr** [comment]
I have updated the markdown file

**Comment by derrek321yr** [comment]
I have updated the markdown file

**Comment by henrydrey** [comment]
I have updated the markdown file

**Pull request closed without merging**
